#!/usr/bin/env zsh

stow_cmd() {
	mkdir -p "$1"
	stow --dir="." --restow --no-folding --target="$1" "$2"
}

firefox_profile="$(ls -d ~/.mozilla/firefox/*.default-release | head -n 1)"

stow_cmd "$firefox_profile/chrome" "firefox-css"

stow_cmd "$HOME/.local/bin" "bin"
stow_cmd "$HOME/.local/colors" "colors"
stow_cmd "$HOME/.local/share/applications" "desktop"

stow_cmd "$HOME/.config/" "config"

mkdir -p "$HOME/.config/zsh/cache"

