
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git
#AurOnly
#BottomUp
RemoveMake
SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
CleanAfter
#UpgradeMenu
#NewsOnUpgrade

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

[bin]
BatFlags = --color never
Sudo = sudo
