read: /home/ivo/.config/aider/CONVENTIONS.md

model-settings-file: .aider/model.settings.yml
model-metadata-file: .aider/model.metadata.json
input-history-file: .aider/input.history
chat-history-file: .aider/chat.history.md
llm-history-file: .aider/llm.history
analytics-log: .aider/analytics.log

analytics: false

dark-mode: true
pretty: true

cache-prompts: true
restore-chat-history: false

suggest-shell-commands: false
auto-lint: true
lint-cmd:
  - "python:ruff format"
  - "python:ruff check"
  - "python:pyright"

gitignore: false

auto-commits: false
dirty-commits: false
attribute-author: false
attribute-committer: false

vim: false

multiline: false
notifications: true
watch-files: true

voice-format: wav
voice-language: en

model: anthropic/claude-sonnet-4-20250514

editor-model: anthropic/claude-sonnet-4-20250514
weak-model: anthropic/claude-3-5-haiku-20241022

