
global-settings
{
	watch-config-file = true;
}

bar
{
	output            = all;
	layer             = top;
	exclusive-zone    = false;
	hidden-mode       = always;

	position          = top;

	size              = 36;
	hidden-size       = 4;
	radius = 12;

	margin = 0;
	border = 0;
	icon-padding = 4;
    indicator-padding = 0;
    indicator-style = rounded-rectangle;

	border-colour = "#00000000";
	background-colour = "#665c54";
    indicator-active-colour = "#00000000";
    indicator-hover-colour = "#00000000";

	spacer
	{
		length = 4;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/devices/video-display.png;
		command = wdisplays;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/apps/multimedia-volume-control.png;
		command = pavucontrol;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/devices/input-keyboard.png;
		command = pkill -RTMIN wvkbd-mobintl;
	}

	spacer
	{
		length = 24;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/apps/system-file-manager.png;
		command = pcmanfm-qt;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/apps/utilities-terminal.png;
		command = foot;
	}

	spacer
	{
		length = 24;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/apps/firefox.png;
		command = firefox;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/apps/transmission.png;
		command = qbittorrent;
	}

	spacer
	{
		length = 24;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/emblems/emblem-music.png;
		command = ymuse;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/emblems/emblem-photos.png;
		command = qimgv;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/emblems/emblem-videos.png;
		command = vlc;
	}

	spacer
	{
		length = 6;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/devices/input-gaming.png;
		command = steamwrap;
	}

	spacer
	{
		length = 24;
	}

	button
	{
		image-path = /usr/share/icons/HighContrast/256x256/actions/window-close.png;
		command = niri msg action close-window;
	}

	spacer
	{
		length = 4;
	}

}
