# WAYLAND ENV

export CALIBRE_USE_SYSTEM_THEME=1
export CLUTTER_BACKEND="wayland"
export DISPLAY=":0"
export ECORE_EVAS_ENGINE="wayland"
export ELM_ENGINE="wayland"
export GDK_BACKEND="wayland"
export KWIN_IM_SHOW_ALWAYS=1
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME="qt6ct"
export QT_SCALE_FACTOR_ROUNDING_POLICY="Round"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QUTE_QT_WRAPPER="PyQt6"
export SDL_VIDEODRIVER="wayland"
export WLR_DRM_NO_ATOMIC=1
export WLR_DRM_NO_MODIFIERS=1
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER="gles2"
export XDG_CURRENT_DESKTOP="niri"
export XDG_SESSION_TYPE="wayland"
