
[server]
## style file for the OSD
# style = "/etc/xdg/swayosd/style.css"

top_margin = 0.9

max_volume = 100

show_percentage = true

playerctl_format = "{title}"
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating
