# LaTeXmk configuration file

# Usage example
# latexmk file.tex

# Main command line options
# -pdf : generate pdf using pdflatex
# -pv  : run file previewer
# -pvc : run file previewer and continually recompile on change
# -C   : clean up by removing all regeneratable files

# Xelatex
# $pdf_mode = 5;

# LuaLaTeX
$pdf_mode = 4;
$postscript_mode = $dvi_mode = 0;

# Use bibtex if a .bib file exists
$bibtex_use = 1;

# Also remove pdfsync files on clean
$clean_ext = 'pdfsync synctex.gz';

set_tex_cmds('-synctex=1 %O %S');
