# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: deepseek:deepseek-chat
temperature: 0.1
top_p: 0.9

save: false

wrap: no
wrap_code: false

clients:
  - type: claude
  - type: openai
  - type: openai-compatible
    name: deepseek
    api_base: https://api.deepseek.com
  - type: openai-compatible
    name: openrouter
    api_base: https://openrouter.ai/api/v1

document_loaders:
  pdf: 'pdftotext $1 -'
  git: >
    sh -c "yek $1 --json | jq '[.[] | { path: .filename, contents: .content }]'"
